export const droppableConfig = [
    { id: 1, rowStart: 1, colStart: 1, colSpan: 1 },
    { id: 2, rowStart: 1, colStart: 5, colSpan: 1 },
    { id: 3, rowStart: 2, colStart: 1, colSpan: 5 },
    { id: 4, rowStart: 3, colStart: 1, colSpan: 5 },
    { id: 5, rowStart: 4, colStart: 1, colSpan: 5 },
    { id: 6, rowStart: 5, colStart: 1, colSpan: 5 },
    { id: 7, rowStart: 6, colStart: 1, colSpan: 5 },
    { id: 8, rowStart: 7, colStart: 1, colSpan: 5 },
    { id: 9, rowStart: 8, colStart: 1, colSpan: 5 },
    { id: 10, rowStart: 9, colStart: 1, colSpan: 5 },
    { id: 11, rowStart: 10, colStart: 1, colSpan: 5 },
    { id: 12, rowStart: 11, colStart: 1, colSpan: 5 },
    { id: 13, rowStart: 12, colStart: 1, colSpan: 5 },
    { id: 14, rowStart: 13, colStart: 1, colSpan: 5 },
    { id: 15, rowStart: 14, colStart: 1, colSpan: 5 },
    { id: 16, rowStart: 15, colStart: 1, colSpan: 5 },
    { id: 17, rowStart: 1, colStart: 3, colSpan: 1 },

  ];